### PR TITLE
Fix README.md for incorrect ResponsiveSizer reference

### PR DESCRIPTION
**Pull request by calvintam236**

### CODE REVIEW

**Comment by calvintam236** [comment]
@TechnoUrmish can you take a look?

**Comment by calvintam236** [comment]
@TechnoUrmish please fix the readme…

**Comment by the-kool-sk** [comment]
Please merge this, it wasted my day. This is must.

**Comment by oza-c** [comment]
@TechnoUrmish Bump up

**Review by KarinBerg — APPROVED** [review]

**Pull request closed without merging**
